### PR TITLE
Fix-Sticky-Footer

### LINKED ISSUE #21: Sticky Footer
Put the footer at bottom, looks odd now.

### PR DESCRIPTION
**Pull request by brianangulo**
Fixes #21

### CODE REVIEW

**Comment by iBotPeaches** [comment]
Ah I see my mistake why CI isn't running for forks. I see a composer change here, but I think you only wanted the css change. 

Either way, I'll push up a fix to correct CI from forks in meantime.

**Review by iBotPeaches — CHANGES_REQUESTED** [review]
Pulled this down a took a look. This does not appear to be a true "sticky" footer, this just forces the content to the bottom of the page. So if the page has more than enough room, it forces a scroll bar.

A sticky footer basically works as
 * If space, locked to bottom
 * If no space, bottom of content
 
 
Welcome to leaf repo, btw.

Screenshot_2021-12-05_11-40-01

**Comment by brianangulo** [comment]
Gotcha thanks! should be sticky now. Was going for "just stay at bottom" approach before lol. Also noticed some empty columns on `home.blade.php` file causing gamer form to be left-aligned instead of centered, left it alone as not sure if it was intentional.

**Review by iBotPeaches — COMMENTED** [review]
This works now as a sticky, so good to go there. I still see that `composer.lock` file updated though and I don't think it should be.

Optionally too, I've been trying to minimize any custom styling instead deferring to any utilities that Bulma has. https://bulma.io/documentation/helpers/

For example, for the `margin-top: auto`, you can just attach `mt-auto` as a class to the footer class in HTML and then we don't need that css.

Still learning flexbox myself, but there seem to be a good deal of utilities that might be able to be used - https://bulma.io/documentation/helpers/flexbox-helpers/

**Comment by brianangulo** [comment]
> Still learning flexbox myself, but there seem to be a good deal of utilities that might be able to be used - https://bulma.io/documentation/helpers/flexbox-helpers/

First time trying out Bulma myself it's not bad. I cleaned it up with classes but could not find height or width utilities though.

**Review by iBotPeaches — APPROVED** [review]

**Comment by iBotPeaches** [comment]
thanks! looks good

**Pull request merged**
